version: 2
pull_request_templates:
  - name: "âœ¨ Feature Request"
    path: "PULL_REQUEST_TEMPLATE/default_template.md"
  - name: "ğŸ Bug Fix"
    path: "PULL_REQUEST_TEMPLATE/team_a_template.md"
  - name: "ğŸ“ Documentation Update"
    path: "PULL_REQUEST_TEMPLATE/team_b_template.md"
